# Generated by Django 2.0 on 2018-03-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blob_name', models.CharField(max_length=50)),
                ('blob_url', models.URLField()),
            ],
        ),
    ]
