# Generated by Django 2.0 on 2018-03-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='blob_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
